### ISSUE TITLE
Todos and priorities

### ISSUE THREAD

**Issue by rodrigorivera** [ColtAllen/lifetimes#14]
Hi everyone,

What are the current development priorities for getting involved?

I was involved in the thread of the original repository back in February. I see that since then, quite some things have happened, and I want to understand where I can get myself involved.

Before the fork, I was working on updating lifetimes with type hinting, and I saw this set as a list of to-dos in the previous thread. Is it still current?

It would be helpful to have a list of open issues to identify where one can contribute.

Does it make sense to contribute with the type hinting? What else remains relevant?

**Comment by ColtAllen** [comment]
Hey @rodrigorivera, good to hear from you again. **The main priority at this time is to utilize [`pymc`](https://github.com/pymc-devs/pymc) as the backend for `lifetimes`**. It'd be a stretch to say I'm rewriting the whole library from scratch, but it sure feels that way. I'd regard type-hinting as something to do going forward, rather than something to go back and add.

I've been adapting [the code written](https://juanitorduz.github.io/bg_nbd_pymc/) by @juanitorduz  in [this working branch](https://github.com/ColtAllen/lifetimes/tree/beta-geo-nbd), and updating it to the latest `pymc` version release, but I'm still testing it out and haven't made any significant commits yet aside from adding a base class. 

I haven't used `pymc` in a few years and have been re-learning it as I go. Knowledge of the library is quite important for anyone wishing to contribute, but fortunately `pymc` has an excellent developer community, with a [message board](https://discourse.pymc.io/) and even [live Zoom sessions](https://www.meetup.com/pymc-online-meetup/events/285640500/). Hope you can make it to the next Zoom event.

**Comment by rodrigorivera** [comment]
Indeed, using pymc represents building the library from scratch. When will be the next Zoom event?
And do I understand correctly that at the moment, there is nothing direct where one can contribute?

**Comment by ColtAllen** [comment]
> And do I understand correctly that at the moment, there is nothing direct where one can contribute?

The `generate_data.py`, `plotting.py`, and `utils.py` modules should remain largely intact, so adding type hinting to those scripts would be helpful. Also the `plotting.plot_calibration_purchases_vs_holdout_purchases` function requires revision because it relies too much on output from the `utils.calibration_and_holdout_data` function.

> When will be the next Zoom event? 

Next Zoom event is at 13:00 UTC time on Thu, 26-May; my previous post contains a link to the event page.

**Comment by ColtAllen** [comment]
Closing this because I've created another issue summarizing how tasks will be organized and prioritized for this repo: https://github.com/ColtAllen/lifetimes/issues/16
