### ISSUE TITLE
Confidence intervals description

### ISSUE THREAD

**Issue by joelcarvalhopribss** [ColtAllen/lifetimes#7]
Hi!

First of all, thanks to @ColtAllen for improving and continuing this amazing library!

After creating a model, we can see confidence intervals, but what is the meaning of r, alpha, a, and b? 

e.i
``betageo_model.confidence_intervals_``

|       | lower 95% bound | upper 95% bound | 
|-------|----------------|-----------------|
| r ?   |      x          |        x         | x
| alpha ? |      x          |           x      | x
| a  ?   |      x          |        x         | x
| b   ?  |       x         |          x       |  x

Thanks!! 👍

**Comment by ColtAllen** [comment]
Hey @joelcarvalhopribss,

`r`, `alpha`, `a`, and `b` are the parameters of the BetaGeo model. Specifically, `r` and `alpha` are the shape and rate parameters of the Gamma distribution used by the model, and `a` and `b` are shape parameters of the Beta distribution from which the model's name is derived. These parameters are currently being estimated via Maximum Likelihood Estimation (MLE), and since they are only best estimates, the confidence intervals give some indication of their reliability.

However, it is important to note that although MLE is an efficient method for model fitting, it is not always stable and may perform poorly. One of the biggest changes I'm making to this library is replacing MLE with a purely Bayesian approach. This should improve model performance and also allow more comprehensive model assessments than the confidence intervals alone.
